Raises ActionController::ParameterMissing when sessions parameters are missing
When no parameters were provided, the sessions controller was raising:

```
NoMethodError: undefined method `[]' for nil:NilClass
```

Fixes #944